--- #YAML:1.0
name:               Params-Check-Faster
version:            0.03
abstract:           Faster implementation of Params::Check, a templated based param validation
author:
    - Damien "dams" Krotkine <dams[at]cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Locale::Maketext::Simple:  0
    Test::More:           0
resources:
    repository:  http://github.com/dams/params-check-faster
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
